version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "schedule-sqs-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ai45xr4lbipn"
s3_prefix = "schedule-sqs-app"
region = "us-west-1"
capabilities = "CAPABILITY_IAM"

